{% set name = "flake8-comprehensions" %}
{% set version = "3.16.0" %}
{% set sha256 = "9cbf789905a8f03f9d350fb82b17b264d9a16c7ce3542b2a7b871ef568cafabe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - flake8 >=3.0,!=3.2.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - 'flake8 --version | grep flake8-comprehensions:'

about:
  home: https://github.com/adamchainz/flake8-comprehensions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin that helps you write better list/set/dict comprehensions.
  dev_url: https://github.com/adamchainz/flake8-comprehensions

extra:
  recipe-maintainers:
    - dopplershift
